<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700" rel="stylesheet">
<link rel="shortcut icon" href="/temp/static/images/favicon.ico">

<style>
    html, body { height: 100%; margin: 0;}
    h1 { margin: 0}
    #container
    {
        position: absolute; top: 0; bottom: 0; left: 0; right: 0;
        display: flex;
        justify-items: center;
        align-items: center;
        justify-content: center;
        background-image: linear-gradient(to bottom right, #fff, #eee);
        font-family: 'Ubuntu', sans-serif;
        font-size: 140%;
        z-index: 999999;
    }
    #sub-container { max-width: 600px; padding: 0 50px}
</style>

<div class="body" id="container">
    <div id="sub-container">
        <h1>Server Error</h1>

        <p>We're sorry! The server encountered an internal error and
            was unable to complete your request. Please try again later.</p>

        <a href="/"> &lt;&lt; try reload homepage</a>
    </div>
</div>

<script>
	document.body.insertBefore(document.getElementById('container'), document.body.firstChild);
	document.title = 'Server Error';
</script>